# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_table_name import OneOfTableName  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfTableName(unittest.TestCase):
    """OneOfTableName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfTableName(self):
        """Test OneOfTableName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_table_name.OneOfTableName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
