# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.table_tag import TableTag  # noqa: E501
from swagger_client.rest import ApiException


class TestTableTag(unittest.TestCase):
    """TableTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTableTag(self):
        """Test TableTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.table_tag.TableTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
