# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.__api import _Api  # noqa: E501
from swagger_client.rest import ApiException


class Test_Api(unittest.TestCase):
    """_Api unit test stubs"""

    def setUp(self):
        self.api = _Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_booking(self):
        """Test case for create_booking

        Бронирование столика  # noqa: E501
        """
        pass

    def test_get_place_by_id(self):
        """Test case for get_place_by_id

        Получить ресторан по ID  # noqa: E501
        """
        pass

    def test_get_places(self):
        """Test case for get_places

        Просмотр списка ресторанов  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
