# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.place import Place  # noqa: E501
from swagger_client.rest import ApiException


class TestPlace(unittest.TestCase):
    """Place unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlace(self):
        """Test Place"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.place.Place()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
