# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.extended_error_message import ExtendedErrorMessage  # noqa: E501
from swagger_client.rest import ApiException


class TestExtendedErrorMessage(unittest.TestCase):
    """ExtendedErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedErrorMessage(self):
        """Test ExtendedErrorMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.extended_error_message.ExtendedErrorMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
