# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.place_tag import PlaceTag  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaceTag(unittest.TestCase):
    """PlaceTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceTag(self):
        """Test PlaceTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.place_tag.PlaceTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
