# coding: utf-8

# flake8: noqa
"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.booking_request import BookingRequest
from swagger_client.models.error_message import ErrorMessage
from swagger_client.models.extended_error_message import ExtendedErrorMessage
from swagger_client.models.inline_response500 import InlineResponse500
from swagger_client.models.one_of_table_name import OneOfTableName
from swagger_client.models.one_ofinline_response500 import OneOfinlineResponse500
from swagger_client.models.place import Place
from swagger_client.models.place_tag import PlaceTag
from swagger_client.models.table import Table
from swagger_client.models.table_tag import TableTag
