# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Place(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'image': 'str',
        'description': 'str',
        'raiting': 'str',
        'tables': 'list[Table]',
        'tag': 'PlaceTag'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'image': 'image',
        'description': 'description',
        'raiting': 'raiting',
        'tables': 'tables',
        'tag': 'Tag'
    }

    def __init__(self, id=None, name=None, image=None, description=None, raiting=None, tables=None, tag=None):  # noqa: E501
        """Place - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._image = None
        self._description = None
        self._raiting = None
        self._tables = None
        self._tag = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.image = image
        self.description = description
        self.raiting = raiting
        if tables is not None:
            self.tables = tables
        if tag is not None:
            self.tag = tag

    @property
    def id(self):
        """Gets the id of this Place.  # noqa: E501

        ID ресторана  # noqa: E501

        :return: The id of this Place.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Place.

        ID ресторана  # noqa: E501

        :param id: The id of this Place.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Place.  # noqa: E501

        Название ресторана  # noqa: E501

        :return: The name of this Place.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Place.

        Название ресторана  # noqa: E501

        :param name: The name of this Place.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def image(self):
        """Gets the image of this Place.  # noqa: E501

        Фото ресторана (URL)  # noqa: E501

        :return: The image of this Place.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this Place.

        Фото ресторана (URL)  # noqa: E501

        :param image: The image of this Place.  # noqa: E501
        :type: str
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def description(self):
        """Gets the description of this Place.  # noqa: E501

        Описание ресторана  # noqa: E501

        :return: The description of this Place.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Place.

        Описание ресторана  # noqa: E501

        :param description: The description of this Place.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def raiting(self):
        """Gets the raiting of this Place.  # noqa: E501

        Рейтинг ресторана  # noqa: E501

        :return: The raiting of this Place.  # noqa: E501
        :rtype: str
        """
        return self._raiting

    @raiting.setter
    def raiting(self, raiting):
        """Sets the raiting of this Place.

        Рейтинг ресторана  # noqa: E501

        :param raiting: The raiting of this Place.  # noqa: E501
        :type: str
        """
        if raiting is None:
            raise ValueError("Invalid value for `raiting`, must not be `None`")  # noqa: E501
        allowed_values = ["ужасно", "плохо", "нормально", "хорошо", "супер"]  # noqa: E501
        if raiting not in allowed_values:
            raise ValueError(
                "Invalid value for `raiting` ({0}), must be one of {1}"  # noqa: E501
                .format(raiting, allowed_values)
            )

        self._raiting = raiting

    @property
    def tables(self):
        """Gets the tables of this Place.  # noqa: E501

        Список столиков  # noqa: E501

        :return: The tables of this Place.  # noqa: E501
        :rtype: list[Table]
        """
        return self._tables

    @tables.setter
    def tables(self, tables):
        """Sets the tables of this Place.

        Список столиков  # noqa: E501

        :param tables: The tables of this Place.  # noqa: E501
        :type: list[Table]
        """

        self._tables = tables

    @property
    def tag(self):
        """Gets the tag of this Place.  # noqa: E501


        :return: The tag of this Place.  # noqa: E501
        :rtype: PlaceTag
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Place.


        :param tag: The tag of this Place.  # noqa: E501
        :type: PlaceTag
        """

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Place, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Place):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
