# coding: utf-8

"""
    Houmwork

    Houmwork for OTUS TTA  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableTag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'place_id': 'int',
        'is_available': 'bool',
        'available_date_time': 'str'
    }

    attribute_map = {
        'place_id': 'placeId',
        'is_available': 'isAvailable',
        'available_date_time': 'availableDateTime'
    }

    def __init__(self, place_id=None, is_available=None, available_date_time=None):  # noqa: E501
        """TableTag - a model defined in Swagger"""  # noqa: E501
        self._place_id = None
        self._is_available = None
        self._available_date_time = None
        self.discriminator = None
        if place_id is not None:
            self.place_id = place_id
        if is_available is not None:
            self.is_available = is_available
        if available_date_time is not None:
            self.available_date_time = available_date_time

    @property
    def place_id(self):
        """Gets the place_id of this TableTag.  # noqa: E501


        :return: The place_id of this TableTag.  # noqa: E501
        :rtype: int
        """
        return self._place_id

    @place_id.setter
    def place_id(self, place_id):
        """Sets the place_id of this TableTag.


        :param place_id: The place_id of this TableTag.  # noqa: E501
        :type: int
        """

        self._place_id = place_id

    @property
    def is_available(self):
        """Gets the is_available of this TableTag.  # noqa: E501


        :return: The is_available of this TableTag.  # noqa: E501
        :rtype: bool
        """
        return self._is_available

    @is_available.setter
    def is_available(self, is_available):
        """Sets the is_available of this TableTag.


        :param is_available: The is_available of this TableTag.  # noqa: E501
        :type: bool
        """

        self._is_available = is_available

    @property
    def available_date_time(self):
        """Gets the available_date_time of this TableTag.  # noqa: E501


        :return: The available_date_time of this TableTag.  # noqa: E501
        :rtype: str
        """
        return self._available_date_time

    @available_date_time.setter
    def available_date_time(self, available_date_time):
        """Sets the available_date_time of this TableTag.


        :param available_date_time: The available_date_time of this TableTag.  # noqa: E501
        :type: str
        """

        self._available_date_time = available_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableTag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableTag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
